export default function ReportsPage() {
  const reports = [
    {
      id: "REP-4012",
      title: "Daily Security Briefing - 2026-06-15",
      type: "Daily Summary",
      status: "GENERATED",
      size: "12 KB",
      createdAt: "2026-06-15 08:00:00"
    },
    {
      id: "REP-3985",
      title: "Incident Response Summary: INC-38102",
      type: "Incident Report",
      status: "COMPLETED",
      size: "8 KB",
      createdAt: "2026-06-15 11:25:00"
    },
    {
      id: "REP-3921",
      title: "Weekly Threat Intelligence Assessment",
      type: "Weekly Compliance",
      status: "ARCHIVED",
      size: "45 KB",
      createdAt: "2026-06-11 18:30:00"
    }
  ];

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "32px" }}>
      <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div>
          <h1 style={{ fontSize: "2rem", fontWeight: 700 }}>SOC Incident Reports</h1>
          <p style={{ color: "var(--text-secondary)" }}>Review and download executive security logs analyses generated by the Report Agent.</p>
        </div>
        <button style={{ 
          background: "linear-gradient(135deg, var(--accent-primary) 0%, var(--accent-secondary) 100%)",
          border: "none",
          color: "var(--bg-primary)",
          padding: "10px 20px",
          borderRadius: "8px",
          fontWeight: 600,
          cursor: "pointer"
        }}>
          + Generate New Report
        </button>
      </header>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: "20px" }}>
        {reports.map((rep) => (
          <div key={rep.id} className="glass-panel" style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <span className="mono" style={{ fontSize: "0.8rem", color: "var(--text-muted)" }}>{rep.id}</span>
              <span className="badge badge-medium">{rep.status}</span>
            </div>
            
            <div>
              <h3 style={{ fontSize: "1.1rem", fontWeight: 600, marginBottom: "4px" }}>{rep.title}</h3>
              <p style={{ color: "var(--text-secondary)", fontSize: "0.85rem" }}>Report Type: {rep.type}</p>
            </div>

            <div style={{ 
              display: "flex", 
              justifyContent: "space-between", 
              alignItems: "center", 
              borderTop: "1px solid var(--border-color)", 
              paddingTop: "12px",
              fontSize: "0.85rem",
              color: "var(--text-muted)" 
            }}>
              <span>File size: {rep.size}</span>
              <span>{rep.createdAt}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
